package org.github.dbjo.rdb.jdbc.remote;

import javax.sql.rowset.CachedRowSet;
import java.sql.*;
import java.util.Objects;

public final class RemoteRocksJdbcStatement implements Statement {
    private final RemoteRocksJdbcConnection conn;
    private boolean closed;
    private int maxRows;
    private CachedRowSet last;

    RemoteRocksJdbcStatement(RemoteRocksJdbcConnection conn) {
        this.conn = Objects.requireNonNull(conn, "conn");
    }

    private void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement closed");
        if (conn.isClosed()) throw new SQLException("Connection closed");
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        last = conn.runQuery(sql, maxRows);
        return last;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        try (ResultSet rs = executeQuery(sql)) {
            return rs != null;
        }
    }

    @Override public ResultSet getResultSet() { return last; }
    @Override public void close() { closed = true; last = null; }
    @Override public boolean isClosed() { return closed; }

    @Override public int getMaxRows() { return maxRows; }
    @Override public void setMaxRows(int max) { this.maxRows = max; }

    @Override public void setFetchSize(int rows) {}
    @Override public int getFetchSize() { return 0; }
    @Override public void setFetchDirection(int direction) {}
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override public void cancel() {}
    @Override public void clearWarnings() {}
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void setMaxFieldSize(int max) {}
    @Override public int getMaxFieldSize() { return 0; }
    @Override public void clearBatch() {}
    @Override public void addBatch(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int[] executeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int getUpdateCount() { return -1; }
    @Override public boolean getMoreResults() { return false; }
    @Override public boolean getMoreResults(int current) { return false; }
    @Override public ResultSet getGeneratedKeys() throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public void setEscapeProcessing(boolean enable) {}
    @Override public void setQueryTimeout(int seconds) {}
    @Override public int getQueryTimeout() { return 0; }
    @Override public void setCursorName(String name) {}
    @Override public Connection getConnection() { return conn; }
    @Override public void setPoolable(boolean poolable) {}
    @Override public boolean isPoolable() { return false; }
    @Override public void closeOnCompletion() {}
    @Override public boolean isCloseOnCompletion() { return true; }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("unwrap");
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
