
DROP TABLE IF EXISTS listener_outbox;
DROP TABLE IF EXISTS listener_consumed_offsets;
DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS client;

CREATE TABLE client (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email    VARCHAR(255) NOT NULL UNIQUE,
  name     VARCHAR(200) NOT NULL,
  version  INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE product (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku       VARCHAR(64) NOT NULL UNIQUE,
  title     VARCHAR(255) NOT NULL,
  price_cents INTEGER NOT NULL CHECK (price_cents >= 0)
);

CREATE TABLE purchase (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,
  qty         INTEGER NOT NULL CHECK (qty > 0),
  ordered_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_purchase_client FOREIGN KEY (client_id) REFERENCES client(id),
  CONSTRAINT fk_purchase_product FOREIGN KEY (product_id) REFERENCES product(id)
);


CREATE TABLE listener_outbox (
  outbox_id VARCHAR(255) PRIMARY KEY,
  partition_key VARCHAR(255) NOT NULL,
  event_payload BLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  published_at TIMESTAMP NULL,
  published_topic VARCHAR(255),
  published_partition INT,
  published_offset BIGINT,
  published_timestamp BIGINT
);

CREATE TABLE listener_consumed_offsets (
  topic VARCHAR(255) NOT NULL,
  partition_no INT NOT NULL,
  offset_value BIGINT NOT NULL,
  offset_metadata VARCHAR(1024),
  PRIMARY KEY (topic, partition_no)
);
