-- Three demo tables: client, product, purchase
-- (HSQLDB supports INFORMATION_SCHEMA for introspection.)

DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS client;

CREATE TABLE client (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email    VARCHAR(255) NOT NULL UNIQUE,
  name     VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE product (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku       VARCHAR(64) NOT NULL UNIQUE,
  title     VARCHAR(255) NOT NULL,
  price_cents INTEGER NOT NULL CHECK (price_cents >= 0)
);

CREATE TABLE purchase (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,
  qty         INTEGER NOT NULL CHECK (qty > 0),
  ordered_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES products(id)
);
