
-- Enums

CREATE TABLE global_region_enum (
  code VARCHAR(8) NOT NULL PRIMARY KEY,     -- EMEA / APAC / AMER
  name VARCHAR(64) NOT NULL,
  sort_order SMALLINT NOT NULL,
  is_active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX ux_global_region_enum_name ON global_region_enum(name);

INSERT INTO global_region_enum (code, name, sort_order, is_active) VALUES ('EMEA', 'Europe, Middle East & Africa', 1, TRUE);
INSERT INTO global_region_enum (code, name, sort_order, is_active) VALUES ('APAC', 'Asia-Pacific',                 2, TRUE);
INSERT INTO global_region_enum (code, name, sort_order, is_active) VALUES ('AMER', 'Americas',                     3, TRUE);

CREATE TABLE country_enum (
  code2 CHAR(2) NOT NULL PRIMARY KEY,
  code3 CHAR(3) NOT NULL,
  numeric_code CHAR(3) NOT NULL,
  name VARCHAR(128) NOT NULL,
  official_name VARCHAR(256) NULL,
  common_name VARCHAR(256) NULL,
  global_region VARCHAR(8) NOT NULL,
  is_active BOOLEAN NOT NULL,
  CONSTRAINT fk_country_enum_global_region
    FOREIGN KEY (global_region) REFERENCES global_region_enum(code)
);
CREATE UNIQUE INDEX ux_country_enum_code3 ON country_enum(code3);
CREATE UNIQUE INDEX ux_country_enum_numeric_code ON country_enum(numeric_code);
CREATE INDEX ix_country_enum_global_region ON country_enum(global_region);

INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AD', 'AND', '020', 'Andorra', 'Principality of Andorra', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AE', 'ARE', '784', 'United Arab Emirates', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AF', 'AFG', '004', 'Afghanistan', 'Islamic Republic of Afghanistan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AG', 'ATG', '028', 'Antigua and Barbuda', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AI', 'AIA', '660', 'Anguilla', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AL', 'ALB', '008', 'Albania', 'Republic of Albania', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AM', 'ARM', '051', 'Armenia', 'Republic of Armenia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AO', 'AGO', '024', 'Angola', 'Republic of Angola', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AQ', 'ATA', '010', 'Antarctica', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AR', 'ARG', '032', 'Argentina', 'Argentine Republic', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AS', 'ASM', '016', 'American Samoa', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AT', 'AUT', '040', 'Austria', 'Republic of Austria', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AU', 'AUS', '036', 'Australia', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AW', 'ABW', '533', 'Aruba', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AX', 'ALA', '248', 'Åland Islands', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('AZ', 'AZE', '031', 'Azerbaijan', 'Republic of Azerbaijan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Republic of Bosnia and Herzegovina', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BB', 'BRB', '052', 'Barbados', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BD', 'BGD', '050', 'Bangladesh', 'People''s Republic of Bangladesh', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BE', 'BEL', '056', 'Belgium', 'Kingdom of Belgium', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BF', 'BFA', '854', 'Burkina Faso', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BG', 'BGR', '100', 'Bulgaria', 'Republic of Bulgaria', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BH', 'BHR', '048', 'Bahrain', 'Kingdom of Bahrain', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BI', 'BDI', '108', 'Burundi', 'Republic of Burundi', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BJ', 'BEN', '204', 'Benin', 'Republic of Benin', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BL', 'BLM', '652', 'Saint Barthélemy', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BM', 'BMU', '060', 'Bermuda', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BN', 'BRN', '096', 'Brunei Darussalam', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BO', 'BOL', '068', 'Bolivia (Plurinational State of)', 'Plurinational State of Bolivia', 'Bolivia', 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BR', 'BRA', '076', 'Brazil', 'Federative Republic of Brazil', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BS', 'BHS', '044', 'Bahamas', 'Commonwealth of the Bahamas', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BT', 'BTN', '064', 'Bhutan', 'Kingdom of Bhutan', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BV', 'BVT', '074', 'Bouvet Island', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BW', 'BWA', '072', 'Botswana', 'Republic of Botswana', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BY', 'BLR', '112', 'Belarus', 'Republic of Belarus', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('BZ', 'BLZ', '084', 'Belize', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CA', 'CAN', '124', 'Canada', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CC', 'CCK', '166', 'Cocos (Keeling) Islands', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CD', 'COD', '180', 'Congo (Democratic Republic of the)', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CF', 'CAF', '140', 'Central African Republic', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CG', 'COG', '178', 'Congo', 'Republic of the Congo', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CH', 'CHE', '756', 'Switzerland', 'Swiss Confederation', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CI', 'CIV', '384', 'Côte d''Ivoire', 'Republic of Côte d''Ivoire', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CK', 'COK', '184', 'Cook Islands', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CL', 'CHL', '152', 'Chile', 'Republic of Chile', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CM', 'CMR', '120', 'Cameroon', 'Republic of Cameroon', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CN', 'CHN', '156', 'China', 'People''s Republic of China', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CO', 'COL', '170', 'Colombia', 'Republic of Colombia', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CR', 'CRI', '188', 'Costa Rica', 'Republic of Costa Rica', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CU', 'CUB', '192', 'Cuba', 'Republic of Cuba', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CV', 'CPV', '132', 'Cabo Verde', 'Republic of Cabo Verde', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CW', 'CUW', '531', 'Curaçao', 'Curaçao', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CX', 'CXR', '162', 'Christmas Island', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CY', 'CYP', '196', 'Cyprus', 'Republic of Cyprus', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('CZ', 'CZE', '203', 'Czech Republic', 'Czech Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DE', 'DEU', '276', 'Germany', 'Federal Republic of Germany', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DJ', 'DJI', '262', 'Djibouti', 'Republic of Djibouti', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DK', 'DNK', '208', 'Denmark', 'Kingdom of Denmark', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DM', 'DMA', '212', 'Dominica', 'Commonwealth of Dominica', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DO', 'DOM', '214', 'Dominican Republic', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('DZ', 'DZA', '012', 'Algeria', 'People''s Democratic Republic of Algeria', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('EC', 'ECU', '218', 'Ecuador', 'Republic of Ecuador', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('EE', 'EST', '233', 'Estonia', 'Republic of Estonia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('EG', 'EGY', '818', 'Egypt', 'Arab Republic of Egypt', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('EH', 'ESH', '732', 'Western Sahara', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ER', 'ERI', '232', 'Eritrea', 'the State of Eritrea', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ES', 'ESP', '724', 'Spain', 'Kingdom of Spain', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ET', 'ETH', '231', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FI', 'FIN', '246', 'Finland', 'Republic of Finland', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FJ', 'FJI', '242', 'Fiji', 'Republic of Fiji', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FK', 'FLK', '238', 'Falkland Islands', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FM', 'FSM', '583', 'Micronesia', 'Federated States of Micronesia', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FO', 'FRO', '234', 'Faroe Islands', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('FR', 'FRA', '250', 'France', 'French Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GA', 'GAB', '266', 'Gabon', 'Gabonese Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GB', 'GBR', '826', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GD', 'GRD', '308', 'Grenada', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GE', 'GEO', '268', 'Georgia', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GF', 'GUF', '254', 'French Guiana', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GG', 'GGY', '831', 'Guernsey', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GH', 'GHA', '288', 'Ghana', 'Republic of Ghana', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GI', 'GIB', '292', 'Gibraltar', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GL', 'GRL', '304', 'Greenland', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GM', 'GMB', '270', 'Gambia', 'Republic of the Gambia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GN', 'GIN', '324', 'Guinea', 'Republic of Guinea', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GP', 'GLP', '312', 'Guadeloupe', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GQ', 'GNQ', '226', 'Equatorial Guinea', 'Republic of Equatorial Guinea', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GR', 'GRC', '300', 'Greece', 'Hellenic Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GT', 'GTM', '320', 'Guatemala', 'Republic of Guatemala', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GU', 'GUM', '316', 'Guam', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GW', 'GNB', '624', 'Guinea-Bissau', 'Republic of Guinea-Bissau', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('GY', 'GUY', '328', 'Guyana', 'Republic of Guyana', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HK', 'HKG', '344', 'Hong Kong', 'Hong Kong Special Administrative Region of China', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HM', 'HMD', '334', 'Heard Island and McDonald Islands', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HN', 'HND', '340', 'Honduras', 'Republic of Honduras', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HR', 'HRV', '191', 'Croatia', 'Republic of Croatia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HT', 'HTI', '332', 'Haiti', 'Republic of Haiti', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('HU', 'HUN', '348', 'Hungary', 'Hungary', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ID', 'IDN', '360', 'Indonesia', 'Republic of Indonesia', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IE', 'IRL', '372', 'Ireland', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IL', 'ISR', '376', 'Israel', 'State of Israel', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IM', 'IMN', '833', 'Isle of Man', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IN', 'IND', '356', 'India', 'Republic of India', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IO', 'IOT', '086', 'British Indian Ocean Territory', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IQ', 'IRQ', '368', 'Iraq', 'Republic of Iraq', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IR', 'IRN', '364', 'Iran', 'Islamic Republic of Iran', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IS', 'ISL', '352', 'Iceland', 'Republic of Iceland', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('IT', 'ITA', '380', 'Italy', 'Italian Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('JE', 'JEY', '832', 'Jersey', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('JM', 'JAM', '388', 'Jamaica', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('JO', 'JOR', '400', 'Jordan', 'Hashemite Kingdom of Jordan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('JP', 'JPN', '392', 'Japan', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KE', 'KEN', '404', 'Kenya', 'Republic of Kenya', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KG', 'KGZ', '417', 'Kyrgyzstan', 'Kyrgyz Republic', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KH', 'KHM', '116', 'Cambodia', 'Kingdom of Cambodia', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KI', 'KIR', '296', 'Kiribati', 'Republic of Kiribati', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KM', 'COM', '174', 'Comoros', 'Union of the Comoros', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KN', 'KNA', '659', 'Saint Kitts And Nevis', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KP', 'PRK', '408', 'Korea (Democratic People''s Republic of)', 'Democratic People''s Republic of Korea', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KR', 'KOR', '410', 'Korea (Republic of)', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KW', 'KWT', '414', 'Kuwait', 'State of Kuwait', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KY', 'CYM', '136', 'Cayman Islands', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('KZ', 'KAZ', '398', 'Kazakhstan', 'Republic of Kazakhstan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LA', 'LAO', '418', 'Laos', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LB', 'LBN', '422', 'Lebanon', 'Lebanese Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LC', 'LCA', '662', 'Saint Lucia', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LI', 'LIE', '438', 'Liechtenstein', 'Principality of Liechtenstein', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LK', 'LKA', '144', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LR', 'LBR', '430', 'Liberia', 'Republic of Liberia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LS', 'LSO', '426', 'Lesotho', 'Kingdom of Lesotho', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LT', 'LTU', '440', 'Lithuania', 'Republic of Lithuania', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LU', 'LUX', '442', 'Luxembourg', 'Grand Duchy of Luxembourg', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LV', 'LVA', '428', 'Latvia', 'Republic of Latvia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('LY', 'LBY', '434', 'Libya', 'Libya', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MA', 'MAR', '504', 'Morocco', 'Kingdom of Morocco', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MC', 'MCO', '492', 'Monaco', 'Principality of Monaco', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MD', 'MDA', '498', 'Moldova', 'Republic of Moldova', 'Moldova', 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ME', 'MNE', '499', 'Montenegro', 'Montenegro', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MF', 'MAF', '663', 'Saint Martin', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MG', 'MDG', '450', 'Madagascar', 'Republic of Madagascar', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MH', 'MHL', '584', 'Marshall Islands', 'Republic of the Marshall Islands', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MK', 'MKD', '807', 'Macedonia', 'Republic of North Macedonia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ML', 'MLI', '466', 'Mali', 'Republic of Mali', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MM', 'MMR', '104', 'Myanmar', 'Republic of Myanmar', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MN', 'MNG', '496', 'Mongolia', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MO', 'MAC', '446', 'Macao', 'Macao Special Administrative Region of China', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MP', 'MNP', '580', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MQ', 'MTQ', '474', 'Martinique', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MR', 'MRT', '478', 'Mauritania', 'Islamic Republic of Mauritania', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MS', 'MSR', '500', 'Montserrat', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MT', 'MLT', '470', 'Malta', 'Republic of Malta', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MU', 'MUS', '480', 'Mauritius', 'Republic of Mauritius', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MV', 'MDV', '462', 'Maldives', 'Republic of Maldives', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MW', 'MWI', '454', 'Malawi', 'Republic of Malawi', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MX', 'MEX', '484', 'Mexico', 'United Mexican States', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MY', 'MYS', '458', 'Malaysia', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('MZ', 'MOZ', '508', 'Mozambique', 'Republic of Mozambique', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NA', 'NAM', '516', 'Namibia', 'Republic of Namibia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NC', 'NCL', '540', 'New Caledonia', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NE', 'NER', '562', 'Niger', 'Republic of the Niger', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NF', 'NFK', '574', 'Norfolk Island', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NG', 'NGA', '566', 'Nigeria', 'Federal Republic of Nigeria', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NI', 'NIC', '558', 'Nicaragua', 'Republic of Nicaragua', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NL', 'NLD', '528', 'Netherlands', 'Kingdom of the Netherlands', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NO', 'NOR', '578', 'Norway', 'Kingdom of Norway', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NP', 'NPL', '524', 'Nepal', 'Federal Democratic Republic of Nepal', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NR', 'NRU', '520', 'Nauru', 'Republic of Nauru', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NU', 'NIU', '570', 'Niue', 'Niue', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('NZ', 'NZL', '554', 'New Zealand', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('OM', 'OMN', '512', 'Oman', 'Sultanate of Oman', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PA', 'PAN', '591', 'Panama', 'Republic of Panama', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PE', 'PER', '604', 'Peru', 'Republic of Peru', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PF', 'PYF', '258', 'French Polynesia', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PG', 'PNG', '598', 'Papua New Guinea', 'Independent State of Papua New Guinea', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PH', 'PHL', '608', 'Philippines', 'Republic of the Philippines', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PK', 'PAK', '586', 'Pakistan', 'Islamic Republic of Pakistan', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PL', 'POL', '616', 'Poland', 'Republic of Poland', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PM', 'SPM', '666', 'Saint Pierre and Miquelon', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PN', 'PCN', '612', 'Pitcairn', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PR', 'PRI', '630', 'Puerto Rico', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PS', 'PSE', '275', 'Palestine', 'the State of Palestine', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PT', 'PRT', '620', 'Portugal', 'Portuguese Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PW', 'PLW', '585', 'Palau', 'Republic of Palau', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('PY', 'PRY', '600', 'Paraguay', 'Republic of Paraguay', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('QA', 'QAT', '634', 'Qatar', 'State of Qatar', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('RE', 'REU', '638', 'Réunion', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('RO', 'ROU', '642', 'Romania', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('RS', 'SRB', '688', 'Serbia', 'Republic of Serbia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('RU', 'RUS', '643', 'Russia', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('RW', 'RWA', '646', 'Rwanda', 'Rwandese Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SA', 'SAU', '682', 'Saudi Arabia', 'Kingdom of Saudi Arabia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SB', 'SLB', '090', 'Solomon Islands', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SC', 'SYC', '690', 'Seychelles', 'Republic of Seychelles', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SD', 'SDN', '729', 'Sudan', 'Republic of the Sudan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SE', 'SWE', '752', 'Sweden', 'Kingdom of Sweden', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SG', 'SGP', '702', 'Singapore', 'Republic of Singapore', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SH', 'SHN', '654', 'Saint Helena', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SI', 'SVN', '705', 'Slovenia', 'Republic of Slovenia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SJ', 'SJM', '744', 'Svalbard', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SK', 'SVK', '703', 'Slovakia', 'Slovak Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SL', 'SLE', '694', 'Sierra Leone', 'Republic of Sierra Leone', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SM', 'SMR', '674', 'San Marino', 'Republic of San Marino', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SN', 'SEN', '686', 'Senegal', 'Republic of Senegal', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SO', 'SOM', '706', 'Somalia', 'Federal Republic of Somalia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SR', 'SUR', '740', 'Suriname', 'Republic of Suriname', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SS', 'SSD', '728', 'South Sudan', 'Republic of South Sudan', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ST', 'STP', '678', 'Sao Tome and Principe', 'Democratic Republic of Sao Tome and Principe', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SV', 'SLV', '222', 'El Salvador', 'Republic of El Salvador', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SX', 'SXM', '534', 'Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SY', 'SYR', '760', 'Syria', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('SZ', 'SWZ', '748', 'Swaziland', 'Kingdom of Eswatini', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TC', 'TCA', '796', 'Turks and Caicos Islands', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TD', 'TCD', '148', 'Chad', 'Republic of Chad', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TF', 'ATF', '260', 'French Southern Territories', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TG', 'TGO', '768', 'Togo', 'Togolese Republic', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TH', 'THA', '764', 'Thailand', 'Kingdom of Thailand', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TJ', 'TJK', '762', 'Tajikistan', 'Republic of Tajikistan', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TK', 'TKL', '772', 'Tokelau', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TL', 'TLS', '626', 'Timor-Leste', 'Democratic Republic of Timor-Leste', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TM', 'TKM', '795', 'Turkmenistan', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TN', 'TUN', '788', 'Tunisia', 'Republic of Tunisia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TO', 'TON', '776', 'Tonga', 'Kingdom of Tonga', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TR', 'TUR', '792', 'Turkey', 'Republic of Turkey', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TT', 'TTO', '780', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TV', 'TUV', '798', 'Tuvalu', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TW', 'TWN', '158', 'Taiwan', 'Taiwan, Province of China', 'Taiwan', 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('TZ', 'TZA', '834', 'Tanzania', 'United Republic of Tanzania', 'Tanzania', 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('UA', 'UKR', '804', 'Ukraine', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('UG', 'UGA', '800', 'Uganda', 'Republic of Uganda', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('UM', 'UMI', '581', 'United States Minor Outlying Islands', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('US', 'USA', '840', 'United States of America', 'United States of America', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('UY', 'URY', '858', 'Uruguay', 'Eastern Republic of Uruguay', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('UZ', 'UZB', '860', 'Uzbekistan', 'Republic of Uzbekistan', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VA', 'VAT', '336', 'Vatican City', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VC', 'VCT', '670', 'Saint Vincent and The Grenadines', NULL, NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VE', 'VEN', '862', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Venezuela', 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VG', 'VGB', '092', 'Virgin Islands (British)', 'British Virgin Islands', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VI', 'VIR', '850', 'Virgin Islands (U.S.)', 'Virgin Islands of the United States', NULL, 'AMER', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VN', 'VNM', '704', 'Viet Nam', 'Socialist Republic of Viet Nam', 'Vietnam', 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('VU', 'VUT', '548', 'Vanuatu', 'Republic of Vanuatu', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('WF', 'WLF', '876', 'Wallis and Futuna', NULL, NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('WS', 'WSM', '882', 'Samoa', 'Independent State of Samoa', NULL, 'APAC', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('YE', 'YEM', '887', 'Yemen', 'Republic of Yemen', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('YT', 'MYT', '175', 'Mayotte', NULL, NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ZA', 'ZAF', '710', 'South Africa', 'Republic of South Africa', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ZM', 'ZMB', '894', 'Zambia', 'Republic of Zambia', NULL, 'EMEA', TRUE);
INSERT INTO country_enum (code2, code3, numeric_code, name, official_name, common_name, global_region, is_active) VALUES ('ZW', 'ZWE', '716', 'Zimbabwe', 'Republic of Zimbabwe', NULL, 'EMEA', TRUE);

CREATE TABLE ccy_enum (
  code CHAR(3) PRIMARY KEY,
  numeric_code CHAR(3) NULL,
  name VARCHAR(128) NOT NULL,
  minor_units SMALLINT NULL,
  is_active BOOLEAN NOT NULL,
  withdrawal_date VARCHAR(32) NULL
);

INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ADP', '020', 'Andorran Peseta', NULL, FALSE, '2003-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AED', '784', 'UAE Dirham', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AFA', '004', 'Afghani', NULL, FALSE, '2003-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AFN', '971', 'Afghani', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ALK', '008', 'Old Lek', NULL, FALSE, '1989-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ALL', '008', 'Lek', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AMD', '051', 'Armenian Dram', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ANG', '532', 'Netherlands Antillean Guilder', NULL, FALSE, '2025-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AOA', '973', 'Kwanza', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AOK', '024', 'Kwanza', NULL, FALSE, '1991-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AON', '024', 'New Kwanza', NULL, FALSE, '2000-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AOR', '982', 'Kwanza Reajustado', NULL, FALSE, '2000-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ARA', '032', 'Austral', NULL, FALSE, '1992-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ARP', '032', 'Peso Argentino', NULL, FALSE, '1985-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ARS', '032', 'Argentine Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ARY', '032', 'Peso', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ATS', '040', 'Schilling', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AUD', '036', 'Australian Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AWG', '533', 'Aruban Florin', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AYM', '945', 'Azerbaijan Manat', NULL, FALSE, '2005-10');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AZM', '031', 'Azerbaijanian Manat', NULL, FALSE, '2005-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('AZN', '944', 'Azerbaijan Manat', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BAD', '070', 'Dinar', NULL, FALSE, '1998-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BAM', '977', 'Convertible Mark', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BBD', '052', 'Barbados Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BDT', '050', 'Taka', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BEC', '993', 'Convertible Franc', NULL, FALSE, '1990-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BEF', '056', 'Belgian Franc', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BEL', '992', 'Financial Franc', NULL, FALSE, '1990-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BGJ', '100', 'Lev A/52', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BGK', '100', 'Lev A/62', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BGL', '100', 'Lev', NULL, FALSE, '2003-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BHD', '048', 'Bahraini Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BIF', '108', 'Burundi Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BMD', '060', 'Bermudian Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BND', '096', 'Brunei Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BOB', '068', 'Boliviano', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BOP', '068', 'Peso boliviano', NULL, FALSE, '1987-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BOV', '984', 'Mvdol', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRB', '076', 'Cruzeiro', NULL, FALSE, '1986-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRC', '076', 'Cruzado', NULL, FALSE, '1989-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRE', '076', 'Cruzeiro', NULL, FALSE, '1993-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRL', '986', 'Brazilian Real', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRN', '076', 'New Cruzado', NULL, FALSE, '1990-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BRR', '987', 'Cruzeiro Real', NULL, FALSE, '1994-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BSD', '044', 'Bahamian Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BTN', '064', 'Ngultrum', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BUK', '104', 'Kyat', NULL, FALSE, '1990-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BWP', '072', 'Pula', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BYB', '112', 'Belarusian Ruble', NULL, FALSE, '2001-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BYN', '933', 'Belarusian Ruble', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BYR', '974', 'Belarusian Ruble', NULL, FALSE, '2017-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('BZD', '084', 'Belize Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CAD', '124', 'Canadian Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CDF', '976', 'Congolese Franc', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CHC', '948', 'WIR Franc (for electronic)', NULL, FALSE, '2004-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CHE', '947', 'WIR Euro', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CHF', '756', 'Swiss Franc', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CHW', '948', 'WIR Franc', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CLF', '990', 'Unidad de Fomento', 4, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CLP', '152', 'Chilean Peso', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CNY', '156', 'Yuan Renminbi', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('COP', '170', 'Colombian Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('COU', '970', 'Unidad de Valor Real', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CRC', '188', 'Costa Rican Colon', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CSD', '891', 'Serbian Dinar', NULL, FALSE, '2006-10');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CSJ', '203', 'Krona A/53', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CSK', '200', 'Koruna', NULL, FALSE, '1993-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CUC', '931', 'Peso Convertible', NULL, FALSE, '2021-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CUP', '192', 'Cuban Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CVE', '132', 'Cabo Verde Escudo', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CYP', '196', 'Cyprus Pound', NULL, FALSE, '2008-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('CZK', '203', 'Czech Koruna', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DDM', '278', 'Mark der DDR', NULL, FALSE, '1990-07 to 1990-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DEM', '276', 'Deutsche Mark', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DJF', '262', 'Djibouti Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DKK', '208', 'Danish Krone', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DOP', '214', 'Dominican Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('DZD', '012', 'Algerian Dinar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ECS', '218', 'Sucre', NULL, FALSE, '2000-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ECV', '983', 'Unidad de Valor Constante (UVC)', NULL, FALSE, '2000-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('EEK', '233', 'Kroon', NULL, FALSE, '2011-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('EGP', '818', 'Egyptian Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ERN', '232', 'Nakfa', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ESA', '996', 'Spanish Peseta', NULL, FALSE, '1978 to 1981');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ESB', '995', '"A" Account (convertible Peseta Account)', NULL, FALSE, '1994-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ESP', '724', 'Spanish Peseta', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ETB', '230', 'Ethiopian Birr', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('EUR', '978', 'Euro', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('FIM', '246', 'Markka', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('FJD', '242', 'Fiji Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('FKP', '238', 'Falkland Islands Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('FRF', '250', 'French Franc', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GBP', '826', 'Pound Sterling', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GEK', '268', 'Georgian Coupon', NULL, FALSE, '1995-10');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GEL', '981', 'Lari', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GHC', '288', 'Cedi', NULL, FALSE, '2008-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GHP', '939', 'Ghana Cedi', NULL, FALSE, '2007-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GHS', '936', 'Ghana Cedi', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GIP', '292', 'Gibraltar Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GMD', '270', 'Dalasi', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GNE', '324', 'Syli', NULL, FALSE, '1989-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GNF', '324', 'Guinean Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GNS', '324', 'Syli', NULL, FALSE, '1986-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GQE', '226', 'Ekwele', NULL, FALSE, '1986-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GRD', '300', 'Drachma', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GTQ', '320', 'Quetzal', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GWE', '624', 'Guinea Escudo', NULL, FALSE, '1978 to 1981');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GWP', '624', 'Guinea-Bissau Peso', NULL, FALSE, '1997-05');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('GYD', '328', 'Guyana Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HKD', '344', 'Hong Kong Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HNL', '340', 'Lempira', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HRD', '191', 'Croatian Dinar', NULL, FALSE, '1995-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HRK', '191', 'Croatian Kuna', NULL, FALSE, '2015-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HTG', '332', 'Gourde', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('HUF', '348', 'Forint', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('IDR', '360', 'Rupiah', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('IEP', '372', 'Irish Pound', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ILP', '376', 'Pound', NULL, FALSE, '1978 to 1981');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ILR', '376', 'Old Shekel', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ILS', '376', 'New Israeli Sheqel', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('INR', '356', 'Indian Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('IQD', '368', 'Iraqi Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('IRR', '364', 'Iranian Rial', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ISJ', '352', 'Old Krona', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ISK', '352', 'Iceland Krona', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ITL', '380', 'Italian Lira', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('JMD', '388', 'Jamaican Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('JOD', '400', 'Jordanian Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('JPY', '392', 'Yen', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KES', '404', 'Kenyan Shilling', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KGS', '417', 'Som', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KHR', '116', 'Riel', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KMF', '174', 'Comorian Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KPW', '408', 'North Korean Won', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KRW', '410', 'Won', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KWD', '414', 'Kuwaiti Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KYD', '136', 'Cayman Islands Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('KZT', '398', 'Tenge', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LAJ', '418', 'Pathet Lao Kip', NULL, FALSE, '1979-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LAK', '418', 'Lao Kip', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LBP', '422', 'Lebanese Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LKR', '144', 'Sri Lanka Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LRD', '430', 'Liberian Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LSL', '426', 'Loti', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LSM', '426', 'Loti', NULL, FALSE, '1985-05');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LTL', '440', 'Lithuanian Litas', NULL, FALSE, '2014-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LTT', '440', 'Talonas', NULL, FALSE, '1993-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LUC', '989', 'Luxembourg Convertible Franc', NULL, FALSE, '1990-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LUF', '442', 'Luxembourg Franc', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LUL', '988', 'Luxembourg Financial Franc', NULL, FALSE, '1990-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LVL', '428', 'Latvian Lats', NULL, FALSE, '2014-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LVR', '428', 'Latvian Ruble', NULL, FALSE, '1994-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('LYD', '434', 'Libyan Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MAD', '504', 'Moroccan Dirham', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MDL', '498', 'Moldovan Leu', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MGA', '969', 'Malagasy Ariary', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MGF', '450', 'Malagasy Franc', NULL, FALSE, '2004-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MKD', '807', 'Denar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MLF', '466', 'Mali Franc', NULL, FALSE, '1984-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MMK', '104', 'Kyat', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MNT', '496', 'Tugrik', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MOP', '446', 'Pataca', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MRO', '478', 'Ouguiya', NULL, FALSE, '2017-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MRU', '929', 'Ouguiya', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MTL', '470', 'Maltese Lira', NULL, FALSE, '2008-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MTP', '470', 'Maltese Pound', NULL, FALSE, '1983-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MUR', '480', 'Mauritius Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MVQ', '462', 'Maldive Rupee', NULL, FALSE, '1989-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MVR', '462', 'Rufiyaa', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MWK', '454', 'Malawi Kwacha', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MXN', '484', 'Mexican Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MXP', '484', 'Mexican Peso', NULL, FALSE, '1993-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MXV', '979', 'Mexican Unidad de Inversion (UDI)', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MYR', '458', 'Malaysian Ringgit', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MZE', '508', 'Mozambique Escudo', NULL, FALSE, '1978 to 1981');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MZM', '508', 'Mozambique Metical', NULL, FALSE, '2006-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('MZN', '943', 'Mozambique Metical', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NAD', '516', 'Namibia Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NGN', '566', 'Naira', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NIC', '558', 'Cordoba', NULL, FALSE, '1990-10');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NIO', '558', 'Cordoba Oro', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NLG', '528', 'Netherlands Guilder', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NOK', '578', 'Norwegian Krone', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NPR', '524', 'Nepalese Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('NZD', '554', 'New Zealand Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('OMR', '512', 'Rial Omani', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PAB', '590', 'Balboa', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PEH', '604', 'Sol', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PEI', '604', 'Inti', NULL, FALSE, '1991-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PEN', '604', 'Sol', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PES', '604', 'Sol', NULL, FALSE, '1986-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PGK', '598', 'Kina', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PHP', '608', 'Philippine Peso', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PKR', '586', 'Pakistan Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PLN', '985', 'Zloty', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PLZ', '616', 'Zloty', NULL, FALSE, '1997-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PTE', '620', 'Portuguese Escudo', NULL, FALSE, '2002-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('PYG', '600', 'Guarani', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('QAR', '634', 'Qatari Rial', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RHD', '716', 'Rhodesian Dollar', NULL, FALSE, '1978 to 1981');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ROK', '642', 'Leu A/52', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ROL', '642', 'Old Leu', NULL, FALSE, '2005-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RON', '946', 'Romanian Leu', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RSD', '941', 'Serbian Dinar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RUB', '643', 'Russian Ruble', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RUR', '810', 'Russian Ruble', NULL, FALSE, '1994-08');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('RWF', '646', 'Rwanda Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SAR', '682', 'Saudi Riyal', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SBD', '090', 'Solomon Islands Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SCR', '690', 'Seychelles Rupee', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SDD', '736', 'Sudanese Dinar', NULL, FALSE, '2007-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SDG', '938', 'Sudanese Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SDP', '736', 'Sudanese Pound', NULL, FALSE, '1998-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SEK', '752', 'Swedish Krona', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SGD', '702', 'Singapore Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SHP', '654', 'Saint Helena Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SIT', '705', 'Tolar', NULL, FALSE, '2007-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SKK', '703', 'Slovak Koruna', NULL, FALSE, '2009-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SLE', '925', 'Leone', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SLL', '694', 'Leone', NULL, FALSE, '2023-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SOS', '706', 'Somali Shilling', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SRD', '968', 'Surinam Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SRG', '740', 'Surinam Guilder', NULL, FALSE, '2003-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SSP', '728', 'South Sudanese Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('STD', '678', 'Dobra', NULL, FALSE, '2017-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('STN', '930', 'Dobra', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SUR', '810', 'Rouble', NULL, FALSE, '1990-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SVC', '222', 'El Salvador Colon', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SYP', '760', 'Syrian Pound', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('SZL', '748', 'Lilangeni', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('THB', '764', 'Baht', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TJR', '762', 'Tajik Ruble', NULL, FALSE, '2001-04');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TJS', '972', 'Somoni', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TMM', '795', 'Turkmenistan Manat', NULL, FALSE, '2009-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TMT', '934', 'Turkmenistan New Manat', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TND', '788', 'Tunisian Dinar', 3, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TOP', '776', 'Pa’anga', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TPE', '626', 'Timor Escudo', NULL, FALSE, '2002-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TRL', '792', 'Old Turkish Lira', NULL, FALSE, '2005-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TRY', '949', 'Turkish Lira', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TTD', '780', 'Trinidad and Tobago Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TWD', '901', 'New Taiwan Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('TZS', '834', 'Tanzanian Shilling', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UAH', '980', 'Hryvnia', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UAK', '804', 'Karbovanet', NULL, FALSE, '1996-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UGS', '800', 'Uganda Shilling', NULL, FALSE, '1987-05');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UGW', '800', 'Old Shilling', NULL, FALSE, '1989 to 1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UGX', '800', 'Uganda Shilling', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('USD', '840', 'US Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('USN', '997', 'US Dollar (Next day)', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('USS', '998', 'US Dollar (Same day)', NULL, FALSE, '2014-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UYI', '940', 'Uruguay Peso en Unidades Indexadas (UI)', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UYN', '858', 'Old Uruguay Peso', NULL, FALSE, '1989-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UYP', '858', 'Uruguayan Peso', NULL, FALSE, '1993-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UYU', '858', 'Peso Uruguayo', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UYW', '927', 'Unidad Previsional', 4, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('UZS', '860', 'Uzbekistan Sum', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VEB', '862', 'Bolivar', NULL, FALSE, '2008-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VED', '926', 'Bolívar Soberano', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VEF', '937', 'Bolivar Fuerte', NULL, FALSE, '2011-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VES', '928', 'Bolívar Soberano', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VNC', '704', 'Old Dong', NULL, FALSE, '1989-1990');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VND', '704', 'Dong', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('VUV', '548', 'Vatu', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('WST', '882', 'Tala', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XAD', '396', 'Arab Accounting Dinar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XAF', '950', 'CFA Franc BEAC', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XAG', '961', 'Silver', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XAU', '959', 'Gold', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XBA', '955', 'Bond Markets Unit European Composite Unit (EURCO)', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XBB', '956', 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XBC', '957', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XBD', '958', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XCD', '951', 'East Caribbean Dollar', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XCG', '532', 'Caribbean Guilder', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XDR', '960', 'SDR (Special Drawing Right)', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XEU', '954', 'European Currency Unit (E.C.U)', NULL, FALSE, '1999-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XFO', NULL, 'Gold-Franc', NULL, FALSE, '2006-10');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XFU', NULL, 'UIC-Franc', NULL, FALSE, '2013-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XOF', '952', 'CFA Franc BCEAO', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XPD', '964', 'Palladium', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XPF', '953', 'CFP Franc', 0, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XPT', '962', 'Platinum', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XRE', NULL, 'RINET Funds Code', NULL, FALSE, '1999-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XSU', '994', 'Sucre', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XTS', '963', 'Codes specifically reserved for testing purposes', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XUA', '965', 'ADB Unit of Account', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('XXX', '999', 'The codes assigned for transactions where no currency is involved', NULL, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('YDD', '720', 'Yemeni Dinar', NULL, FALSE, '1991-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('YER', '886', 'Yemeni Rial', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('YUD', '890', 'New Yugoslavian Dinar', NULL, FALSE, '1990-01');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('YUM', '891', 'New Dinar', NULL, FALSE, '2003-07');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('YUN', '890', 'Yugoslavian Dinar', NULL, FALSE, '1995-11');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZAL', '991', 'Financial Rand', NULL, FALSE, '1995-03');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZAR', '710', 'Rand', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZMK', '894', 'Zambian Kwacha', NULL, FALSE, '2012-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZMW', '967', 'Zambian Kwacha', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZRN', '180', 'New Zaire', NULL, FALSE, '1999-06');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZRZ', '180', 'Zaire', NULL, FALSE, '1994-02');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWC', '716', 'Rhodesian Dollar', NULL, FALSE, '1989-12');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWD', '716', 'Zimbabwe Dollar (old)', NULL, FALSE, '2006-08');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWG', '924', 'Zimbabwe Gold', 2, TRUE, NULL);
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWL', '932', 'Zimbabwe Dollar', NULL, FALSE, '2024-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWN', '942', 'Zimbabwe Dollar (new)', NULL, FALSE, '2006-09');
INSERT INTO ccy_enum (code, numeric_code, name, minor_units, is_active, withdrawal_date) VALUES ('ZWR', '935', 'Zimbabwe Dollar', NULL, FALSE, '2009-06');

-- Demo tables: client, product, purchase
-- (HSQLDB supports INFORMATION_SCHEMA for introspection.)

DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS client;

CREATE TABLE client (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email    VARCHAR(255) NOT NULL UNIQUE,
  name     VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE product (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku       VARCHAR(64) NOT NULL UNIQUE,
  title     VARCHAR(255) NOT NULL,
  price_cents INTEGER NOT NULL CHECK (price_cents >= 0)
);

CREATE TABLE purchase (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id   BIGINT NOT NULL,
  product_id  BIGINT NOT NULL,
  qty         INTEGER NOT NULL CHECK (qty > 0),
  ordered_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_purchase_client FOREIGN KEY (client_id) REFERENCES client(id),
  CONSTRAINT fk_purchase_product FOREIGN KEY (product_id) REFERENCES product(id)
);
