package org.github.dbjo.rdb.jdbc;

import javax.sql.rowset.CachedRowSet;
import java.sql.*;
import java.util.Objects;

public final class RocksJdbcStatement implements Statement {
    private final RocksJdbcConnection conn;
    private boolean closed = false;
    private int maxRows = 0;
    private CachedRowSet last;

    public RocksJdbcStatement(RocksJdbcConnection conn) {
        this.conn = Objects.requireNonNull(conn, "conn");
    }

    private void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement closed");
        if (conn.isClosed()) throw new SQLException("Connection closed");
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        last = conn.engine().query(sql, maxRows);
        return last;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        ResultSet rs = executeQuery(sql);
        return rs != null;
    }

    @Override public ResultSet getResultSet() { return last; }

    @Override public void close() { closed = true; last = null; }
    @Override public boolean isClosed() { return closed; }

    @Override public void setMaxRows(int max) { this.maxRows = Math.max(0, max); }
    @Override public int getMaxRows() { return maxRows; }

    // --- read-only driver defaults ---
    @Override public int executeUpdate(String sql) throws SQLException { throw new SQLFeatureNotSupportedException("read-only"); }
    @Override public Connection getConnection() { return conn; }
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchDirection(int direction) {}
    @Override public int getFetchSize() { return 0; }
    @Override public void setFetchSize(int rows) {}
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getUpdateCount() { return -1; }
    @Override public boolean getMoreResults() { return false; }
    @Override public void setQueryTimeout(int seconds) {}
    @Override public int getQueryTimeout() { return 0; }
    @Override public void cancel() {}
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() {}
    @Override public void setCursorName(String name) {}

    // --- unsupported variants ---
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override public int getResultSetHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override public boolean getMoreResults(int current) { return false; }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return null;
    }

    @Override public void setEscapeProcessing(boolean enable) {}
    @Override public void setMaxFieldSize(int max) {}
    @Override public int getMaxFieldSize() { return 0; }

    @Override public void addBatch(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }
    @Override public void clearBatch() {}
    @Override public int[] executeBatch() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override public void setPoolable(boolean poolable) {}
    @Override public boolean isPoolable() { return false; }
    @Override public void closeOnCompletion() {}
    @Override public boolean isCloseOnCompletion() { return false; }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return Statement.super.getLargeUpdateCount();
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        Statement.super.setLargeMaxRows(max);
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        return Statement.super.getLargeMaxRows();
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        return Statement.super.executeLargeBatch();
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        return Statement.super.executeLargeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return Statement.super.executeLargeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return Statement.super.executeLargeUpdate(sql, columnIndexes);
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return Statement.super.executeLargeUpdate(sql, columnNames);
    }

    @Override
    public String enquoteLiteral(String val) throws SQLException {
        return Statement.super.enquoteLiteral(val);
    }

    @Override
    public String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException {
        return Statement.super.enquoteIdentifier(identifier, alwaysQuote);
    }

    @Override
    public boolean isSimpleIdentifier(String identifier) throws SQLException {
        return Statement.super.isSimpleIdentifier(identifier);
    }

    @Override
    public String enquoteNCharLiteral(String val) throws SQLException {
        return Statement.super.enquoteNCharLiteral(val);
    }

    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("unwrap");
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
