package org.github.dbjo.rdb.jdbc.catalog;

import org.github.dbjo.rdb.jdbc.RocksJdbcConnection;

import java.sql.*;

public final class RocksJdbcStatement implements Statement {
    private final RocksJdbcConnection conn;
    private boolean closed = false;

    private int maxRows = 0;
    private ResultSet last;

    public RocksJdbcStatement(RocksJdbcConnection conn) {
        this.conn = conn;
    }

    private void ensureOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
        if (conn.isClosed()) throw new SQLException("Connection is closed");
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ensureOpen();
        last = conn.runQuery(sql, maxRows);
        return last;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        ensureOpen();
        last = conn.runQuery(sql, maxRows);
        return true; // we always return a ResultSet for supported SQL
    }

    @Override
    public ResultSet getResultSet() {
        return last;
    }

    @Override
    public void close() {
        closed = true;
        last = null;
    }

    @Override
    public int getMaxRows() {
        return maxRows;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        if (max < 0) throw new SQLException("maxRows must be >= 0");
        this.maxRows = max;
    }

    @Override
    public Connection getConnection() {
        return conn;
    }

    private static SQLFeatureNotSupportedException unsup() {
        return new SQLFeatureNotSupportedException("Not supported in rudimentary Rocks JDBC");
    }

    @Override public int executeUpdate(String sql) throws SQLException { throw unsup(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { /* ignore */ }
    @Override public int getQueryTimeout() { return 0; }
    @Override public void cancel() throws SQLException { throw unsup(); }
    @Override public SQLWarning getWarnings() { return null; }
    @Override public void clearWarnings() {}
    @Override public void setCursorName(String name) throws SQLException { throw unsup(); }
    @Override public int getUpdateCount() { return -1; }
    @Override public boolean getMoreResults() { return false; }
    @Override public void setFetchDirection(int direction) {}
    @Override public int getFetchDirection() { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchSize(int rows) {}
    @Override public int getFetchSize() { return 0; }
    @Override public int getResultSetConcurrency() { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public void addBatch(String sql) throws SQLException { throw unsup(); }
    @Override public void clearBatch() {}
    @Override public int[] executeBatch() throws SQLException { throw unsup(); }
    @Override public boolean getMoreResults(int current) { return false; }
    @Override public ResultSet getGeneratedKeys() throws SQLException { throw unsup(); }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { throw unsup(); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { throw unsup(); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { throw unsup(); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public int getResultSetHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }
    @Override public boolean isClosed() { return closed; }
    @Override public void setPoolable(boolean poolable) {}
    @Override public boolean isPoolable() { return false; }
    @Override public void closeOnCompletion() {}
    @Override public boolean isCloseOnCompletion() { return false; }
    @Override public void setEscapeProcessing(boolean enable) {}
    @Override public int getMaxFieldSize() { return 0; }
    @Override public void setMaxFieldSize(int max) {}
    @Override public void setLargeMaxRows(long max) throws SQLException { setMaxRows((int)Math.min(Integer.MAX_VALUE, max)); }
    @Override public long getLargeMaxRows() { return getMaxRows(); }
    @Override public long[] executeLargeBatch() throws SQLException { throw unsup(); }
    @Override public long executeLargeUpdate(String sql) throws SQLException { throw unsup(); }
    @Override public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException { throw unsup(); }
    @Override public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException { throw unsup(); }
    @Override public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException { throw unsup(); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLException("unwrap not supported"); }
    @Override public boolean isWrapperFor(Class<?> iface) { return false; }
}
