spring:
  datasource:
    url: jdbc:hsqldb:mem:dbjo;DB_CLOSE_DELAY=-1
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: SA
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:static-data.sql

server:
  port: 8433

rocks:
  path: ./data/rocksdb
